# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/tests/terraform/infra-build", "/tests/terraform/vm-build"
    schedule:
      interval: "weekly"
      day: "sunday"
    open-pull-requests-limit: 5 # default, let's see how we go
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"] # let's have more control over major changes
